name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - "5.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build Lice libraries and executables
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Build Lice documentation
        if: matrix.os == 'ubuntu-latest'
        run: opam exec -- dune build @doc

      - name: Upload playground.bc.js
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: playground
          path: _build/default/doc/ocaml/playground.bc.js

      - name: Upload odoc documentation
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: |
            _build/default/doc/_doc/_html/lice
            _build/default/doc/_doc/_html/odoc.support

  lint-fmt:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"
          dune-cache: true

      - uses: ocaml/setup-ocaml/lint-fmt@v2

  deploy-site:
    needs: [build, lint-fmt]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download playground.bc.js
        uses: actions/download-artifact@v4
        with:
          name: playground
          path: doc/assets

      - name: Download odoc documentation
        uses: actions/download-artifact@v4
        with:
          name: doc
          path: doc/doc
      
      - name: Deploy to VPS Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "/doc/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.PATH }}
          EXCLUDE: "/ocaml/, *.md"
